CREATE VIEW Zapytanie2 AS 
SELECT NAZWA, SUMA FROM
(
  SELECT T.NAZWA AS NAZWA ,SUM(N.KWOTA) AS SUMA FROM 
  TURNIEJ T JOIN TURNIEJ_NAGRODA TN ON TN.TURNIEJ_ID = T.ID JOIN NAGRODA N ON N.ID = tn.nagroda_id GROUP BY NAZWA
)
WHERE ROWNUM <= 3 ORDER BY SUMA DESC